### PR TITLE
(Proposal) Ditch DatePeriod

### PR DESCRIPTION
**Pull request by imbrish**
Relying on `DatePeriod` seems to be just cluttering constructor without bringing any benefits.

- Our iterator can simply use `$this->current->add($this->interval)`
- Parsing `An ISO 8601` format is just matter of `explode('/', $format)`?
- Separate constructors will be easier to maintain:
```php
static create($startDateOrString, $intervalOrString, $endDateOrStringOrRecurrences)
static createFromISO($format)
static between($startDateOrString, $endDateOrString, $intervalOrString = null) // from now to date
static since($startDateOrString, $intervalOrString = null) // from date to now
static until($endDateOrString, $intervalOrString = null) // from now to date
static last($recurrences, $intervalOrString = null) // x recurrences of interval to now
static next($recurrences, $intervalOrString = null) // x recurrences of interval from now
__construct($startDate, $interval, $endDateOrRecurrences) // by default start inclusive end exclusive
```
- We will be able to ensure that number of recurrences will be returned no matter the filters (wonder what happens when filters are mutually exclusive... infinite loop I guess?)
- We will be able to specify number of recurrences, start and end date no matter the input (will be time expensive, as we need to go through whole thing with filters to calculate that)

Just a proposal without any actual code so you can let me know your opinion on this.

### CODE REVIEW

**Comment by imbrish** [comment]
Just so I can find https://github.com/briannesbitt/Carbon/pull/1257

**Comment by imbrish** [comment]
1. First let me clarify the last point:

	Currently getters will return null for some constructor arguments.

	```php
	new CarbonPeriod($start, $interval, $end); // all good
	new CarbonPeriod($start, $interval, $recurrences); // end null
	new CarbonPeriod($spec); // all null

	```

	To fix that for all versions of PHP we will need to do the parsing ourselves anyway.

2. In favor of custom iterator

	I agree that by using `DatePeriod` we get rid of the responsibility to fix whatever can go wrong with custom iterator, which always sounds like a good idea.

	But I don't think the base class is that well maintained in the first place. That weird bugfix that disallowed changing properties? Uhm. Also it won't parse all valid ISO formats anyway (unlimited recurrences, interval and end date).

	ISO seems really simple to parse, we have all the necessary tools provided by `Carbon` and `CarbonInterval`. Custom iteration doesn't seem that difficult either, however dates always seem simple and then they kick your ass, so I'm curious what you think could go wrong with that. If we rely on using built-in `add`, then do we have to worry about DST, leap seconds or any other rarities?

	It's true that all the features I mentioned can be done without ditching `DatePeriod`. But if we leave it and build stuff all around it, we are open for inconsistencies. Mistakes may not be apparent and will be difficult to track when getters say one thing, and actual iterator does something else.

3. Back to ideas

	Making recurrences into a filter is spot on! I think it would be even preferable to disallow them from constructors altogether and be explicit:

	```php
	$i->recurrences(3)->filter(...) // valid
	$i->filter(...)->recurrences(3) // valid but different!
	```

	Implementation super easy:

	```php
	public function recurrences($i) {
	    return $this->filter(function ($current, $key) {
	    	return key < $i;
	    });
	}
	```

	This brings me an another idea. Maybe infinite loops are not that bad when did on purpose?
	What if we allowed creating periods starting or ending on given date and infinitely looping forwards or backwards until loop is broken? Could be useful when you don't know which date you're looking for.

	Lastly, getters could be "divided" into two groups, one "source" (start date, interval, end date, recurrences) and other "final" (first date, last date, count).

**Comment by kylekatarnls** [comment]
OK to ditch DatePeriod :)

OK to put recurrences in a dedicated method and implement it as a filter.

OK for our a spec parsing if you feel confortable with it.

Careful with "final" first/last/count, it means we have to calculate them in a way that may imply to fulfill the iteration, it could be heavy. We should make the user aware of that. Maybe by provide access to them only via a `render/resolve/calculate` method. Maybe simply `->toArray()`, so the user is aware he's turning the whole period into an array, then he can simply call `reset()`, `end()` or `count()` on it to get first, last and count.

**Comment by imbrish** [comment]
I'll be away during the weekend, but will take care of this sometime early next week.

**Comment by imbrish** [comment]
Soon after weekend became 10 days after all ;)

**Pull request closed without merging**
